export const Icons = {
    RECTANGLE: "./icons/rectangle.svg",
    US_FLAG: "./icons/Ic_US_Flag.svg",
    ARRWOCLOCKWISE: "./icons/ArrowsClockwise.svg",
    LAYER21: "./icons/layer-2-1.svg",
    LAYER2: "./icons/layer-2.svg",
    TRANSNSFERINOUT: "./icons/TransferInOut.svg",
    USER: "./icons/user.svg",
    AIRTICKET: "./icons/AirTicket.svg",
    CULRURAL: "./icons/Cultural.svg",
    ACCOMODATION: "./icons/accomodations.svg",
    HAPPY: "./icons/happy.svg",
    ELEMENT1: "./icons/element-1.svg",
    PHONE: "./icons/phone.svg",
    BRAZILFLAG: "./icons/BrazilFlag.svg",
    UAEFLAG: "./icons/UAEFlag.svg",
    GLOBE: "./icons/Globe.svg",
    INSTAGRAMLOGO: "./icons/InstagramLogo.svg",
    TESTMONIALLOGO: "./icons/TestMonialLogo.svg",
}


export const Images = {
    GROUP5: "./images/group-5.png",
    HOMEBG: "./images/HomeBg.png",
    LOGO: "./images/logo.png",
    LOGOFOOTER: "./images/LOGOFOOTER.png",
    GROUP3: "./images/group-3.png",
    STOPOVER: "./images/Stopover.png",
    STOPOVER2: "./images/StopOver2.png",
    STOPOVER3: "./images/StopOver3.png",
    TESTMONIAL1: "./images/TestMonial1.png",
    TESTCARD1: "./images/TESTCARD1.png",
    TESTMONIAL2: "./images/TestMonial2.png",
    TESTCARD2: "./images/TESTCARD2.png",
    TESTMONIAL3: "./images/TestMonial3.png",
    TESTCARD3: "./images/TESTCARD3.png",
    WHYDOHABACK: "./images/whydohaback.png",
    FOUNDERIMAGE: "./images/FounderImage.png",
    CONTACTUS: "./images/CONTACTUS.png",
    BOOKSTAY: "./images/BookStay.png",
    FounderLTOP: "./images/FounderLTOP.png",
    FounderRTOP: "./images/FounderRTOP.png",
    FounderRBOTTOM: "./images/FounderRBOTTOM.png",
    FounderLBOTTOM: "./images/FounderLBOTTOM.png",
    FounderCENTRE: "./images/FounderCENTRE.png",
    FAVICON: "./images/favicon.png",
}